/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BarcodeSeries = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'values' : IDL.Vec(IDL.Text),
  'format' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSeries' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteSeries' : IDL.Func([IDL.Nat], [], []),
  'getSeries' : IDL.Func([IDL.Nat], [BarcodeSeries], ['query']),
  'listSeries' : IDL.Func([], [IDL.Vec(BarcodeSeries)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BarcodeSeries = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'values' : IDL.Vec(IDL.Text),
    'format' : IDL.Text,
  });
  
  return IDL.Service({
    'createSeries' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteSeries' : IDL.Func([IDL.Nat], [], []),
    'getSeries' : IDL.Func([IDL.Nat], [BarcodeSeries], ['query']),
    'listSeries' : IDL.Func([], [IDL.Vec(BarcodeSeries)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };